.TH wl 1
.SH NAME
wl \- Work Logger. Allows for easy management of time tracking based on tmux sessions
.SH SYNOPSIS
.B wl
.SH DESCRIPTION
.B wl
is a set of ksh functions to easily manage a timesheet in terminal.
It is set up to run inside tmux sessions, and tracks the time in a file of the name of the tmux session inside the
.I ~/work_logs/
directory.
.SH OPTIONS
.TP
.BR \-N " "[\fIfile_name\fR]
Create a new log file. Including the [old file] will concatenate the old file to the new one.
.TP
.BR \-a\fR
Archive the current time sheet and remove all excess sheets locally and remotely (currently works with box's webdav with cadaver and expect installed).
.TP
.BR \-t\fR " "[\fIfile_name\fR]
Print the current log (same action as wl without args), or file_name's log if it is entered.
.TP
.BR \-s\fR
Start a new row in the time sheet with the current date and time (rounded to 15 minutes).
.TP
.BR \-f\fR " "[\fI"comment"\fR]
End the current row in the time sheet with the current time (rounded to 15 minutes). If a comment is added, append that as well.
.TP
.BR \-c\fR
Print current time block (last start in file to current time).
.TP
.BR \-i\fR " "\fIlog_entry\fR
Print the full comment for a specific log entry.
.TP
.BR \-d\fR " "[\fImm/dd/yy(date)\fR]
Print the date and total time for a date. Prints today's stats if no date is included.
.TP
.BR \-v\fR
Edit the current work log in vi(m). Sets 
.TP
.SH TODO
.BR wl.conf
contains any specific settings needed to customize the interaction for wl.
This encompasses remote backup/saving, directory location, etc... It hasn't been set up yet, but is on the to do list


