.TH wl 1
.SH NAME
wl \- Work Logger. Allows for easy management of time tracking based on tmux sessions
.SH SYNOPSIS
.B wl
[\fB-acdefilmnstx\fR] [\fB-d \fImm/dd/yy(date)\fR] [\fB-f \fI"comment"\fR] [\fB-i \fIitem_number\fR] [\fB-l \fIfile_name\fR] [\fB-m \fIfile_name]
.SH DESCRIPTION
.B wl
is a set of ksh functions to easily manage a timesheet in terminal.
It is set up to run inside tmux sessions, and tracks the time in a file of the name of the tmux session inside the
.I ~/work_logs/
directory.
.SH OPTIONS
.TP
.BR \-a\fR
Archive the current time sheet and remove all excess sheets.
.TP
.BR \-c\fR
Print current time block (last start in file to current time).
.TP
.BR \-d\fR " "\fImm/dd/yy(date)\fR
Print the date and total time for a date (mm/yy/dd format).
.TP
.BR \-e\fR
Edit the current work log in vi(m). Make sure to set end of line and binary options appropriately. when working with a current row open, or it will write the file with an EOL character, which will move the next finish input to the next row, making things ugly
.TP
.BR \-f\fR " "\fI"comment"\fR
Finish the current row in the time sheet with the current time (rounded to 15 minutes).
.TP
.BR \-i\fR " "\fIlog_id\fR
Print the full comment for a specific log entry.
.TP
.BR \-l\fR " "\fIfile_name\fR
Load the file and work on that instead of the current session's file.
.TP
.BR \-m\fR "\fIfile_name\fR
Append file into the current sheet
.TP
.BR \-n\fR
Create a new log file.
.TP
.BR \-r\fR
(Re)compile the tex file into PDF format. This is useful if you manually edit the tex file then need to compile the PDF again
.TP
.BR \-s\fR
Begin a new row in the time sheet with the current date and time (rounded to 15 minutes).
.TP
.BR \-t\fR " "\fIfile_name\fR
Print the current log (same action as wl without args), or file_name's log if it is entered.
.TP
.BR \-x\fr
Build LaTeX file and export to pdf (requires texinfo)
.TP
.SH TODO
.BR wl.conf
contains any specific settings needed to customize the interaction for wl.
This encompasses remote backup/saving, directory location, etc... It hasn't been set up yet, but is on the to do list

Automate the -e option to know whether it is the end of the line or not (to set for writing)

